### ISSUE TITLE
is it possible to spawn them for a longer amount of time?

### ISSUE THREAD

**Issue by VeratoxMC** [SCRN-VRC/Raymarched-GPU-Particles-with-Screenspace-Physics#2]
Hello,

since i think this is the only way to contact you, i would like to ask if it is possible to spawn the particles for a longer amount of time?

Thank you.

**Comment by SCRN-VRC** [comment]
https://github.com/SCRN-VRC/Raymarched-GPU-Particles-with-Screenspace-Physics/blob/c788616f53858f49a25e70d5f97b404755b66b0b/Simple%20SSPhysics/Shaders/SSPQueue4998.shader#L155

Change the 0.01 to something smaller like 0.005 if you want extend the time by 2x. Since the # of particles is fixed, it'll look disjointed.
